drop table if exists roles cascade;
drop table if exists users cascade;
drop table if exists orders cascade;
drop table if exists past_orders cascade;
drop table if exists news cascade;
drop table if exists responses cascade;

CREATE TABLE news (
                      id int8 NOT NULL,
                      author varchar(255) NULL,
                      new_image varchar(255) NULL,
                      pub_date date NULL,
                      "text" varchar(255) NULL,
                      title varchar(255) NULL,
                      CONSTRAINT news_pkey PRIMARY KEY (id)
);

CREATE TABLE users (
                       id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                       activation_code varchar(255) NULL,
                       active bool NOT NULL,
                       email varchar(255) NULL,
                       "name" varchar(255) NULL,
                       "password" varchar(255) NULL,
                       surname varchar(255) NULL,
                       username varchar(255) NULL,
                       CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE roles (
                       id int8 NOT NULL,
                       "role" varchar(255) NULL,
                       CONSTRAINT roles_pkey PRIMARY KEY (id)
);


-- public.roles внешние включи

ALTER TABLE public.roles ADD CONSTRAINT fkfwd8notqt2avggaputa06qln5 FOREIGN KEY (id) REFERENCES users(id);

CREATE TABLE orders (
                        id int8 NOT NULL,
                        author varchar(255) NULL,
                        count int4 NOT NULL,
                        description varchar(255) NULL,
                        expected_date date NULL,
                        is_approved bool NOT NULL,
                        max_price float8 NOT NULL,
                        product_name varchar(255) NULL,
                        provider int4 NULL,
                        CONSTRAINT orders_pkey PRIMARY KEY (id)
);


-- public.orders внешние включи

ALTER TABLE public.orders ADD CONSTRAINT orders_provider_fkey FOREIGN KEY (provider) REFERENCES roles(id);

CREATE TABLE past_orders (
                             id int8 NOT NULL,
                             author varchar(255) NULL,
                             count int4 NOT NULL,
                             description varchar(255) NULL,
                             expected_date date NULL,
                             max_price float8 NOT NULL,
                             product_name varchar(255) NULL,
                             provider int4 NULL,
                             status varchar(255) NULL,
                             CONSTRAINT past_orders_pkey PRIMARY KEY (id)
);


-- public.past_orders внешние включи

ALTER TABLE public.past_orders ADD CONSTRAINT past_orders_provider_fkey FOREIGN KEY (provider) REFERENCES roles(id);

CREATE TABLE responses (
                           id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                           id_order int8 NULL,
                           id_supp int8 NULL,
                           CONSTRAINT responses_pkey PRIMARY KEY (id)
);


-- public.responses внешние включи

ALTER TABLE public.responses ADD CONSTRAINT fkaq3b59w0j8lr1qapkktmapben FOREIGN KEY (id_supp) REFERENCES users(id);
ALTER TABLE public.responses ADD CONSTRAINT fksvy5tbopvs8u29lulctdv66jf FOREIGN KEY (id_order) REFERENCES orders(id) ON DELETE CASCADE ON UPDATE CASCADE;